=== ygnstudio/bing_wallpaper_archive/schemas/index.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Bing Wallpaper Index",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["date", "title"],
    "properties": {
      "date": { "type": "string", "pattern": "^[0-9]{8}$" },
      "title": { "type": "string", "minLength": 1 },
      "copyright": { "type": "string" },
      "category": { "type": "string" },
      "color": { "type": "string" },
      "thumbnail": { "type": "string" },
      "uhd": { "type": ["boolean", "null"] },
      "url": { "type": "string", "format": "uri" },
      "copyrightlink": { "type": "string", "format": "uri" },
      "urlbase": { "type": "string" }
    },
    "additionalProperties": false
  }
}

=== ygnstudio/bing_wallpaper_archive/data/2016.json
[
 {
  "date": "20161231",
  "title": "北海道的一对长尾林鸮",
  "copyright": "北海道的一对长尾林鸮，日本 (© JTB Media Creation, Inc./Alamy Stock Photo)",
  "category": "动物",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161231.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.WinterOwls_ZH-CN11633542284_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.WinterOwls_ZH-CN11633542284"
 },
 {
  "date": "20161230",
  "title": "斯图加特市附近的霍亨索伦城堡",
  "copyright": "斯图加特市附近的霍亨索伦城堡，德国 (© Jürgen Eisele/500px)",
  "category": "建筑",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161230.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.ZellerHorn_ZH-CN7123868469_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.ZellerHorn_ZH-CN7123868469"
 },
 {
  "date": "20161229",
  "title": "贾斯珀国家公园的阿萨巴斯卡河",
  "copyright": "贾斯珀国家公园的阿萨巴斯卡河，加拿大 (© Ron Harris/Offset)",
  "category": "风景",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161229.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.AthabascaCanyon_ZH-CN11032342866_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.AthabascaCanyon_ZH-CN11032342866"
 },
 {
  "date": "20161228",
  "title": "阿寒国立公园的丹顶鹤",
  "copyright": "阿寒国立公园的丹顶鹤，日本北海道 (© Vincent Munier/Minden Pictures)",
  "category": "动物",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161228.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.GrusJaponensis_ZH-CN8553179454_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.GrusJaponensis_ZH-CN8553179454"
 },
 {
  "date": "20161227",
  "title": "特罗姆瑟的色彩缤纷的房子",
  "copyright": "特罗姆瑟的色彩缤纷的房子，挪威 (© Tomasz Misiukiewicz/500px)",
  "category": "风景",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161227.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.ColorfulTromso_ZH-CN9894938772_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.ColorfulTromso_ZH-CN9894938772"
 },
 {
  "date": "20161226",
  "title": "南安普敦公园",
  "copyright": "南安普敦公园，南安普敦，英格兰 (© David Baker/Gallery Stock)",
  "category": "风景",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161226.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.SouthamptonCommon_ZH-CN8102690225_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.SouthamptonCommon_ZH-CN8102690225"
 },
 {
  "date": "20161225",
  "title": "特伦蒂诺-上阿迪杰的一个圣诞市集",
  "copyright": "特伦蒂诺-上阿迪杰的一个圣诞市集，南蒂罗尔，意大利 (© Carlo Trolese/500px)",
  "category": "建筑",
  "color": "红",
  "thumbnail": "thumbnails/2016/12/20161225.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.SnowGlobeVideo_ZH-CN8461656803_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.SnowGlobeVideo_ZH-CN8461656803"
 },
 {
  "date": "20161224",
  "title": "雪地里的红鹿",
  "copyright": "雪地里的红鹿 (© Getty Images)",
  "category": "风景",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161224.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.BelarusDeer_ZH-CN10349578779_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.BelarusDeer_ZH-CN10349578779"
 },
 {
  "date": "20161223",
  "title": "爱丁堡一家叫做The Dome的夜店",
  "copyright": "爱丁堡一家叫做The Dome的夜店，苏格兰 (© Marty McKillop/500px)",
  "category": "建筑",
  "color": "红",
  "thumbnail": "thumbnails/2016/12/20161223.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.TheDomeEdinburgh_ZH-CN11993142817_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.TheDomeEdinburgh_ZH-CN11993142817"
 },
 {
  "date": "20161222",
  "title": "曼哈顿海滩码头",
  "copyright": "曼哈顿海滩码头，加利福尼亚州，美国 (© Mat Rick Photography/Aurora Photos)",
  "category": "交通",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161222.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.ManhattanBeach_ZH-CN10916747728_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.ManhattanBeach_ZH-CN10916747728"
 },
 {
  "date": "20161221",
  "title": "【今日冬至】中国古人滑冰图",
  "copyright": "【今日冬至】中国古人滑冰图 (© Stock Connection/REX/Shutterstock)",
  "category": "风景",
  "color": "橙",
  "thumbnail": "thumbnails/2016/12/20161221.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.AncientpeopleSkating_ZH-CN10472124556_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.AncientpeopleSkating_ZH-CN10472124556"
 },
 {
  "date": "20161220",
  "title": "一株被灯带装饰了的树形仙人掌",
  "copyright": "一株被灯带装饰了的树形仙人掌，亚利桑那州 (© Gallery Stock)",
  "category": "植物",
  "color": "多彩",
  "thumbnail": "thumbnails/2016/12/20161220.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.SaguaroLights_ZH-CN11691459871_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.SaguaroLights_ZH-CN11691459871"
 },
 {
  "date": "20161219",
  "title": "埃尔迈拉市的一个树农场",
  "copyright": "埃尔迈拉市的一个树农场，爱达荷州，美国 (© Woods Wheatcroft/Aurora Photos)",
  "category": "植物",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161219.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.ElmiraTreeFarm_ZH-CN8716369223_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.ElmiraTreeFarm_ZH-CN8716369223"
 },
 {
  "date": "20161218",
  "title": "巨大海葵上的一枚海星",
  "copyright": "巨大海葵上的一枚海星， 西巴丹岛附近，婆罗洲 (© Norbert Wu/Minden Pictures)",
  "category": "动物",
  "color": "紫",
  "thumbnail": "thumbnails/2016/12/20161218.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.CandyCaneSeaStar_ZH-CN8947157877_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.CandyCaneSeaStar_ZH-CN8947157877"
 },
 {
  "date": "20161217",
  "title": "被纸袋灯照亮的酒店",
  "copyright": "被纸袋灯照亮的酒店，洛雷托，圣达菲，新墨西哥州，美国 (© Ian Shive/Tandem Stills + Motion)",
  "category": "建筑",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161217.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.Farolitos_ZH-CN12055626406_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.Farolitos_ZH-CN12055626406"
 },
 {
  "date": "20161216",
  "title": "雪地里的日落",
  "copyright": "雪地里的日落，瑞士 (© Alexander Dragunov/500px)",
  "category": "风景",
  "color": "多彩",
  "thumbnail": "thumbnails/2016/12/20161216.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.SwitzerlandSunset_ZH-CN8198492507_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.SwitzerlandSunset_ZH-CN8198492507"
 },
 {
  "date": "20161215",
  "title": "大特尔诺沃",
  "copyright": "大特尔诺沃，保加利亚 (© valentinrussanov/Getty Images)",
  "category": "建筑",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161215.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.VelikoTarnovo_ZH-CN11165433151_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.VelikoTarnovo_ZH-CN11165433151"
 },
 {
  "date": "20161214",
  "title": "帕萨米里亚国家公园的黑夜猴",
  "copyright": "帕萨米里亚国家公园的黑夜猴，秘鲁 (© Cyril Ruoso/Minden Pictures)",
  "category": "风景",
  "color": "黄",
  "thumbnail": "thumbnails/2016/12/20161214.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.MicoDeNoche_ZH-CN10514469675_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.MicoDeNoche_ZH-CN10514469675"
 },
 {
  "date": "20161213",
  "title": "马林维尔的Fromme-Birney Round Barn博物馆的内顶",
  "copyright": "马林维尔的Fromme-Birney Round Barn博物馆的内顶，堪萨斯州，美国 (© Garret Suhrie/Tandem Stills + Motion)",
  "category": "建筑",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161213.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.CircularBarn_ZH-CN10350401093_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.CircularBarn_ZH-CN10350401093"
 },
 {
  "date": "20161212",
  "title": "陆地卫星8号的红外照片",
  "copyright": "陆地卫星8号的红外照片， 摄于哈萨克斯坦的油田 (© NASA)",
  "category": "太空",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161212.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.KazakhstanNasa_ZH-CN9791985430_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.KazakhstanNasa_ZH-CN9791985430"
 },
 {
  "date": "20161211",
  "title": "巴尔切沃村庄的近郊",
  "copyright": "巴尔切沃村庄的近郊，奥尔什丁市，波兰 (© jesiotr9/Getty Images)",
  "category": "建筑",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161211.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.WarmiaPoland_ZH-CN13324541925_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.WarmiaPoland_ZH-CN13324541925"
 },
 {
  "date": "20161210",
  "title": "梅萨维德国家公园的悬崖宫正在进行的圣诞灯节",
  "copyright": "梅萨维德国家公园的悬崖宫正在进行的圣诞灯节，科罗拉多州，美国 (© Richard Ellis/Alamy)",
  "category": "风景",
  "color": "棕",
  "thumbnail": "thumbnails/2016/12/20161210.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.CliffPalaceLuminara_ZH-CN10279459718_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.CliffPalaceLuminara_ZH-CN10279459718"
 },
 {
  "date": "20161209",
  "title": "正在征服少女峰的攀登者们",
  "copyright": "正在征服少女峰的攀登者们，伯尔尼阿尔卑斯山，瑞士 (© plainpicture/Cultura/Lost Horizon Images)",
  "category": "人物",
  "color": "橙",
  "thumbnail": "thumbnails/2016/12/20161209.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.JungfrauClimbers_ZH-CN11867441596_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.JungfrauClimbers_ZH-CN11867441596"
 },
 {
  "date": "20161208",
  "title": "湾仔区的行人天桥",
  "copyright": "湾仔区的行人天桥，香港 (© timestock22/Nimia)",
  "category": "交通",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161208.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.RoundWalkway_ZH-CN10197024907_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.RoundWalkway_ZH-CN10197024907"
 },
 {
  "date": "20161207",
  "title": "艾德林根高地上的晨雾",
  "copyright": "艾德林根高地上的晨雾，普法芬温克尔，巴伐利亚，德国 (© WestEnd61/REX/Shutterstock)",
  "category": "风景",
  "color": "蓝",
  "thumbnail": "thumbnails/2016/12/20161207.webp",
  "uhd": false,
  "url": "https://cdn.bimg.cc/bing/2016/OHR.AidlingerHoehe_ZH-CN11764360351_1920x1080.jpg",
  "copyrightlink": "",
  "urlbase": "/th?id=OHR.AidlingerHoehe_ZH-CN11764360351"
 },
 {
  "date": "20161206",
